name: Build Gimel Studio

# Controls when the action will run.
on:
  push:
    tags: 'v*'

  workflow_dispatch:


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: sudo apt-get install libsdl2-2.0-0
    - run: python pip -m install pyinstaller
    - run: python pip -m install opencv-python
    - run: python pip -m install numpy
    - run: python pip -m install scipy
    - run: python pip -m install pillow
    - run: python -m pip install "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl"

    # Prepare the release
    - name: Prepare release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/GimelStudio/
        dest: GimelStudio-Linux64.zip

    # Actually make the release
    - name: Uploading release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./GimelStudio-Linux64.zip
        asset_name: GimelStudio-Linux64.zip
        tag: ${{ github.ref }}



  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt


    # Prepare the release
    - name: Prepare release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/GimelStudio/
        dest: GimelStudio-Windows64.zip

    # Actually make the release
    - name: Uploading release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./GimelStudio-Windows64.zip
        asset_name: GimelStudio-Windows64.zip
        tag: ${{ github.ref }}