name: Build

# Controls when the action will run. 
on:
  push:
    tags: 'v*'
    
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: ubuntu_20
          - os: windows-latest
            name: windows

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      # Install the project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      
      # Build with PyInstaller
      - name: Compile using pyinstaller
        run: |
          pyinstaller -n "GimelStudio" --hidden-import pkg_resources.py2_warn "src/main.py"
      
      # Prepare the release
      - name: Prepare release
        uses: papeloto/action-zip@v1
        with:
          files: ./dist/GimelStudio/
          dest: GimelStudio-${{ matrix.name }}.zip

      # Actually make the release
      - name: Uploading release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./GimelStudio-${{ matrix.name }}.zip
          asset_name: ${{ matrix.name }}.zip
          tag: ${{ github.ref }}
