name: Build Gimel Studio

# Controls when the action will run.
on:
  push:
    tags: 'v*'

  workflow_dispatch:


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: sudo apt-get install libsdl2-2.0-0
    - run: python -m pip install pyinstaller
    - run: python -m pip install --find-links ${WHEELS} wxPython
      env:
        WHEELS: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04
    - run: python -m pip install opencv-python
    - run: python -m pip install scipy


    # Prepare the release
    - name: Prepare release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/GimelStudio/
        dest: GimelStudio-${{ matrix.name }}.zip

    # Actually make the release
    - name: Uploading release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./GimelStudio-${{ matrix.name }}.zip
        asset_name: ${{ matrix.name }}.zip
        tag: ${{ github.ref }}



  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt


    # Prepare the release
    - name: Prepare release
      uses: papeloto/action-zip@v1
      with:
        files: ./dist/GimelStudio/
        dest: GimelStudio-${{ matrix.name }}.zip

    # Actually make the release
    - name: Uploading release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./GimelStudio-${{ matrix.name }}.zip
        asset_name: ${{ matrix.name }}.zip
        tag: ${{ github.ref }}